services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=bettergr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bettergr2425
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    ports:
      - "80:80"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=5432
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=auth.bettergr.org
      - KC_HOSTNAME_PORT=80
      - KC_HTTP_PORT=80
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      front-tier:
        aliases:
          - auth.bettergr.org
      back-tier:
        aliases:
          - auth.bettergr.org

  students:
    build: ../students-microservice
    ports:
      - "50051:50051"
    environment:
      - AUTH_ISSUER=http://auth.bettergr.org/realms/betterGR
      - DSN=postgres://postgres:bettergr2425@db:5432/bettergr?sslmode=disable
      - DP_NAME=bettergr
      - GRPC_PORT=50051
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - back-tier
    restart: on-failure

  courses:
    build: ../courses-microservice
    ports:
      - "50052:50052"
    environment:
      - AUTH_ISSUER=http://auth.bettergr.org/realms/betterGR
      - DSN=postgres://postgres:bettergr2425@db:5432/bettergr?sslmode=disable
      - DP_NAME=bettergr
      - GRPC_PORT=50052
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - back-tier
    restart: on-failure

  grades:
    build: ../grades-microservice
    ports:
      - "50053:50053"
    environment:
      - AUTH_ISSUER=http://auth.bettergr.org/realms/betterGR
      - DSN=postgres://postgres:bettergr2425@db:5432/bettergr?sslmode=disable
      - DP_NAME=bettergr
      - GRPC_PORT=50053
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - back-tier
    restart: on-failure


  staff:
    build: ../staff-microservice
    ports:
      - "50054:50054"
    environment:
      - AUTH_ISSUER=http://auth.bettergr.org/realms/betterGR
      - DSN=postgres://postgres:bettergr2425@db:5432/bettergr?sslmode=disable
      - DP_NAME=bettergr
      - GRPC_PORT=50054
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - back-tier
    restart: on-failure


  homework:
    build: ../homework-microservice
    ports:
      - "50055:50055"
    environment:
      - AUTH_ISSUER=http://auth.bettergr.org/realms/betterGR
      - DSN=postgres://postgres:bettergr2425@db:5432/bettergr?sslmode=disable
      - DP_NAME=bettergr
      - GRPC_PORT=50055
    depends_on:
      keycloak:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - back-tier
    restart: on-failure

networks:
  front-tier: {}
  back-tier: {}
